# version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/config.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "6173:6173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/app
    depends_on:
      - server